 * Environment: development
 * Debug mode: on
Traceback (most recent call last):
  File "/home/server/Documents/ocr/sandhi/sandhivenv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/server/Documents/ocr/sandhi/sandhivenv/lib/python3.7/site-packages/flask/cli.py", line 990, in main
    cli.main(args=sys.argv[1:])
  File "/home/server/Documents/ocr/sandhi/sandhivenv/lib/python3.7/site-packages/flask/cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "/home/server/Documents/ocr/sandhi/sandhivenv/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/server/Documents/ocr/sandhi/sandhivenv/lib/python3.7/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/server/Documents/ocr/sandhi/sandhivenv/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/server/Documents/ocr/sandhi/sandhivenv/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/server/Documents/ocr/sandhi/sandhivenv/lib/python3.7/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/server/Documents/ocr/sandhi/sandhivenv/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/server/Documents/ocr/sandhi/sandhivenv/lib/python3.7/site-packages/flask/cli.py", line 857, in run_command
    extra_files=extra_files,
  File "/home/server/Documents/ocr/sandhi/sandhivenv/lib/python3.7/site-packages/werkzeug/serving.py", line 982, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
